version: '3'
services:
    iris:
        build: .
        ports:
          - "52773:52773"
          - "51773:51773"
        volumes:
          - "./:/datavol"

    # m1:
    #     image: "eclipse-mosquitto"
    #     ports:
    #         - "7000:1883"
    #     links:
    #         - m2
    # m2: 
    #     image: "eclipse-mosquitto"
    #     ports:
    #         - "8000:1883"
