version: '3.7'
services:
  iris:
      hostname: iris
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - 52773:52773         
      environment:
      - TZ=JST-9
      volumes:
        - "./datavol:/datavol"
        - "./c-src:/home/irisowner/src"
        - ./datavol/share:/home/irisowner/share 

  apache:
    image: httpd:2.4
    init: true
    hostname: apache
    ports:
      - 80:80        
    environment:
    - TZ=JST-9
    volumes:
    - ./datavol/App:/usr/local/apache2/htdocs/ 

  python:
    restart: always
    build:
      context: python
    working_dir: '/root/'
    tty: true
    environment:
    - TZ=JST-9
    volumes:
    - ./datavol/share:/root/share 

  netgw:
    image: intersystemsdc/pexservice:latest
    build:
      context: dotnet
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 55556:55556
    environment:
      - TZ=JST-9    