version: '3'
services:
    iris:
        build: .
        ports:
          - "52773:52773"
          - "51773:51773"
          - "1883:1883"
          - "9001:9001"         
        volumes:
          - "./:/datavol"


