Class dc.SimpleClass Extends %Library.PersistentXEP [ Final, GeneratedBy = %FOI.Schema, ProcedureBlock ]
{

Parameter IMPORTTIMESTAMP = "12/16/2021 04:01:00";

Parameter IMPORTFLAGS = 1;

Property "<myUInt>k__BackingField" As %Library.Integer;

Property "<myULong>k__BackingField" As %Library.BigInt;

Property "<myUBool>k__BackingField" As %Library.Boolean;

Property "<myUDouble>k__BackingField" As %Library.Double;

Property "<myUFloat>k__BackingField" As %Library.Float;

Property "<myUBytes>k__BackingField" As %Library.RawString;

Property "<myUString>k__BackingField" As %Library.String;

Property "<myInt>k__BackingField" As %Library.Integer;

Property "<myLong>k__BackingField" As %Library.BigInt;

Property "<myBool>k__BackingField" As %Library.Boolean;

Property "<myDouble>k__BackingField" As %Library.Double;

Property "<myFloat>k__BackingField" As %Library.Float;

Property "<myBytes>k__BackingField" As %Library.RawString;

Property "<myString>k__BackingField" As %Library.String;

Property "<myArray>k__BackingField" As list Of %Library.RawString(STORAGEDEFAULT = "list");

Property "<myMap>k__BackingField" As array Of %Library.String(STORAGEDEFAULT = "list");

}
